sudo: false

language: go

matrix:
  include:
    - go: 1.5

before_script:
  - go vet ./...

install:
  - go get github.com/tools/godep
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - make verify
